version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  rustapp:
    container_name: rustapp
    image: metratrj/rustapp:latest
    build:
      context: ./
      dockerfile: backend.dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432
        DATABASE_NAME: postgres
        HOST: 0.0.0.0
        PORT: 8000

volumes:
  db_data: { }