name: Rust

on:
  push:
    branches: ["dev"]
    paths:
      - "api/**"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: ["dev"]
    paths:
      - "api/**"
      - ".github/workflows/rust.yml"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: "Install dependencies Ubuntu"
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends openssl build-essential libmariadb-dev-compat libpq-dev libssl-dev pkg-config

      # Show environment
      - name: "Show environment"
        run: |
          rustc -vV
          cargo -vV

      - run: rustup toolchain install stable --profile minimal

      # Enable Rust Caching
      - uses: Swatinem/rust-cache@v2.7.3
        with:
          # Use a custom prefix-key to force a fresh start. This is sometimes needed with bigger changes.
          # Like changing the build host from Ubuntu 20.04 to 22.04 for example.
          # Only update when really needed! Use a <year>.<month>[.<inc>] format.
          prefix-key: "v2024.05-rust"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Set Rust caching env vars only on non-release runs
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Build
        run: |
          cargo prisma generate
          cargo build --verbose
